/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "rideshare-20200818203058-hostingbucket-rideshare",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://diy7ehjrixmbx.cloudfront.net",
    "region": "us-east-2",
    "userPoolId": "us-east-2_XdyDueQqj",
    "userPoolWebClientId": "3v7p0hnhiqhnptu97vb1su4h8q"
};


export default awsmobile;
